[build]
  # Build from the client directory
  base = "client"
  
  # Build command - install all dependencies including dev dependencies
  command = "npm install --include=dev && npm run build"
  
  # Publish directory
  publish = "dist"

[build.environment]
  # Set Node.js version
  NODE_VERSION = "18"
  NODE_ENV = "production"
  NPM_CONFIG_PRODUCTION = "false"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 